# Generated by Django 3.2.5 on 2021-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('IdNumber', models.IntegerField()),
                ('Pin', models.CharField(max_length=100)),
            ],
        ),
    ]
