# Generated by Django 3.2.5 on 2021-07-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_register_postaladdress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
