# Generated by Django 3.2.5 on 2021-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_auto_20210728_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='service',
            field=models.CharField(choices=[('Renewal Of Driving Licence', 'Renew Driving Licence'), ('Temporary Permit Application', 'Temporary Permit'), ('PassPort Application', 'PassPort Application')], default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rest',
            name='service',
            field=models.CharField(choices=[('Business Cards Design', 'Business Cards Design'), ('Invoice Cards Design', 'Invoice Cards Design'), ('Delivery Cards Design', 'Delivery Cards Design'), ('Wedding Cards Design', 'Wedding Cards Design'), ('Funeral Cards Design', 'Funeral Cards Design'), ('Banners Design', 'Banners Design')], default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='service',
            field=models.CharField(choices=[('Individual Return', 'Individual Return'), ('Company Tax Return', 'Company Tax Return'), ('VAT Return Filing', 'VAT Return Filing'), ('PAYE Return Filing', 'PAYE Return Filing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rest',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
